version: 1.0.{build}

clone_folder: C:\block\polimorfismver2

build:

install:
    - git submodule -q update --init --recursive

build_script:
    - cd C:\block\polimorfismver2
    - md build
    - cd build
    - cmake -G"CodeBlocks - MinGW Makefies" ..
    - cmake --build . --config debug

after_build:

test_script:
    - cmd: ctest -C Debug -VV
